name: build-push-image

on:
  push:
    tags:
      - "v"
  pull_request:
    branches:
      - "development"
      - "uat"
      - "master"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v2
      - 
        name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: brandonslp/url-shortener
          labels: |
            org.opencontainers.image.description=Commit: ${{ github.sha }} - Branch: ${{ steps.extract_branch.outputs.branch }}
          tags: |
            type=ref,event=pr
            type=semver,pattern={{raw}}
      -       
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      -     
        name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - 
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./ 
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          labels: ${{ steps.meta.outputs.labels }} 
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
      -
        name: Image digest
        run: |
          echo "Image:"
          echo -e "\t-Digest: ${{ steps.docker_build.outputs.digest }}"
          echo -e "\t-Tags: ${{ steps.meta.outputs.tags }}"
          echo -e "\t-Description: Commit: ${{ github.sha }} - Branch: ${{ steps.extract_branch.outputs.branch }}"